# Generated by Django 4.2.27 on 2026-01-29 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id_enrollment', models.BigAutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=10)),
                ('ni', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('group_td', models.CharField(blank=True, max_length=10, null=True)),
                ('group_tp', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'enrollments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id_filiere', models.BigAutoField(primary_key=True, serialize=False)),
                ('filiere_name', models.CharField(max_length=100)),
                ('branch_short_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'filiere',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id_student', models.BigAutoField(primary_key=True, serialize=False)),
                ('massar_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cin', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('last_name_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('module_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('coefficient', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('id_filiere', models.ForeignKey(blank=True, db_column='id_filiere', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filiere')),
            ],
            options={
                'db_table': 'modules',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id_grade', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_sn', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_sr', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('id_enrollment', models.ForeignKey(blank=True, db_column='id_enrollment', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.enrollments')),
            ],
            options={
                'db_table': 'grades',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='enrollments',
            name='id_student',
            field=models.ForeignKey(blank=True, db_column='id_student', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.students'),
        ),
        migrations.AddField(
            model_name='enrollments',
            name='module_code',
            field=models.ForeignKey(blank=True, db_column='module_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modules'),
        ),
    ]
