# Generated by Django 4.2.27 on 2026-01-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='annee_bac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='province_bac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='type_bac',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
