# Generated by Django 4.2.27 on 2026-01-29 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_students_annee_bac_students_province_bac_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomesAnterieurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_diplome', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('filiere', models.CharField(max_length=100)),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mention', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='core.students')),
            ],
            options={
                'db_table': 'diplomes_anterieurs',
            },
        ),
    ]
