# Generated by Django 4.2.27 on 2026-01-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diplomesanterieurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='mention_bac',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
