# Generated by Django 4.2.27 on 2026-01-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_students_mention_bac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='mention_bac',
            field=models.CharField(choices=[('Passable', 'Passable'), ('Assez Bien', 'Assez Bien'), ('Bien', 'Bien'), ('Très Bien', 'Très Bien')], default='Bien', max_length=15),
        ),
    ]
