# Generated by Django 4.2.27 on 2026-01-29 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_students_mention_bac'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_suivi', models.EmailField(max_length=255, verbose_name='Email pour le suivi')),
                ('champ_a_modifier', models.CharField(choices=[('first_name_fr', 'Prénom (Français)'), ('last_name_fr', 'Nom (Français)'), ('first_name_ar', 'Prénom (Arabe)'), ('last_name_ar', 'Nom (Arabe)'), ('date_naissance', 'Date de Naissance'), ('lieu_naissance', 'Lieu de Naissance'), ('telephone', 'Numéro de Téléphone'), ('cin', 'narte d identite national'), ('massar_code', 'code_massar'), ('email', 'Adresse Email Personnel')], max_length=50)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=255)),
                ('nouvelle_valeur', models.CharField(max_length=255)),
                ('justificatif', models.FileField(upload_to='reclamations/preuves/')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Rejeté', 'Rejeté')], default='En attente', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
            ],
        ),
    ]
