# Generated by Django 4.2.27 on 2026-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_students_lieu_naissance_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='commune',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='pays',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
