# Generated by Django 4.2.27 on 2026-01-30 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_students_commune_students_pays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='students',
            old_name='commune',
            new_name='commune_naissance',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='pays',
            new_name='pays_naissance',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='ancienne_valeur',
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='champ_a_modifier',
            field=models.CharField(choices=[('last_name_fr', 'Nom (Français)'), ('last_name_ar', 'الإسم العائلي'), ('first_name_fr', 'Prénom (Français)'), ('first_name_ar', 'الإسم الشخصي'), ('birth_date', 'Date de Naissance'), ('lieu_naissance', 'Lieu de Naissance'), ('commune_naissance', 'Commune de Naissance'), ('pays_naissance', 'Pays de Naissance'), ('cin', 'CIN'), ('massar_code', 'Code Massar'), ('phone', 'Téléphone'), ('email', 'Email Personnel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='email_suivi',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='core.students'),
        ),
        migrations.AlterModelTable(
            name='reclamation',
            table='reclamation',
        ),
    ]
