# Generated by Django 4.1.13 on 2026-03-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_reclamation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='email_suivi',
        ),
    ]
