# Generated by Django 4.1.13 on 2026-03-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_reclamation_email_suivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='ancienne_valeur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='email_suivi',
            field=models.EmailField(default='test@test.com', max_length=255, verbose_name='Email pour le suivi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='champ_a_modifier',
            field=models.CharField(choices=[('first_name_fr', 'Prénom (Français)'), ('last_name_fr', 'Nom (Français)'), ('first_name_ar', 'Prénom (Arabe)'), ('last_name_ar', 'Nom (Arabe)'), ('date_naissance', 'Date de Naissance'), ('lieu_naissance', 'Lieu de Naissance'), ('telephone', 'Numéro de Téléphone'), ('cin', 'narte d identite national'), ('massar_code', 'code_massar'), ('email', 'Adresse Email Personnel')], max_length=50),
        ),
        migrations.CreateModel(
            name='DemandeRecorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarque', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Traitée', 'Traitée'), ('Rejetée', 'Rejetée')], default='En cours', max_length=20)),
                ('nouvelle_note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('commentaire_admin', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modules')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
            ],
            options={
                'db_table': 'demande_recorrection',
                'managed': True,
            },
        ),
    ]
